# Generated by Django 4.1.7 on 2023-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.JSONField(verbose_name=models.URLField(blank=True, db_index=True, unique=True)),
        ),
    ]
