# Generated by Django 4.1.7 on 2023-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_event_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.JSONField(),
        ),
    ]
